cv:
  kind: time
  n_splits: 5
  shuffle: false
hpo:
  grid:
    max_depth:
    - null
    - 6
    - 10
    - 14
    min_samples_leaf:
    - 1
    - 2
    - 4
    min_samples_split:
    - 2
    - 5
    - 10
    n_estimators:
    - 200
    - 400
    - 800
  method: grid
  metric: neg_root_mean_squared_error
  random_state: 42
  task: regression
leakage:
  detect: true
  r2_threshold: 0.9
  strategy: redefine_target
  suspect_features:
  - 'PROMEDIO EDAD HOMBRE '
  - 'PROMEDIO EDAD MUJER '
  target_base: PROMEDIO EDAD NB
split:
  date_col: anio
  test_start: 2019
  train_end: 2018
